C_SOURCES := \
	os/os_misc.c \
	os/os_process.c \
	os/os_time.c \
	tgsi/tgsi_build.c \
	tgsi/tgsi_dump.c \
	tgsi/tgsi_exec.c \
	tgsi/tgsi_info.c \
	tgsi/tgsi_iterate.c \
	tgsi/tgsi_parse.c \
	tgsi/tgsi_scan.c \
	tgsi/tgsi_strings.c \
	tgsi/tgsi_text.c \
	tgsi/tgsi_transform.c \
	tgsi/tgsi_ureg.c \
	tgsi/tgsi_util.c \
	util/u_format_srgb.c \
	util/u_format_table.c \
	util/u_hash_table.c


